stages:
  - codestyle
  - Tests

# needs an image with chrome,selenium,python3.10
default:
  image:
    name: joyzoursky/python-chromedriver:3.9-alpine-selenium

sonar:
  stage: codestyle
  image:
    name: sonarsource/sonar-scanner-cli:latest

  variables:
    SONAR_AUTH_TOKEN: $SONAR_AUTH_TOKEN
    SONAR_HOST_URL: https://sonar.tkhtechnology.com
  script:
    - sonar-scanner -Dsonar.login=${SONAR_AUTH_TOKEN}
  tags:
    - docker_shared
  only:
    - merge_requests
    - schedules

test-main:
  stage: Tests
  before_script:
    - pip install pipenv
    - pip install pyenv
    - pipenv install
  script:
    - pipenv run pytest pages/main
  tags:
    - docker_shared
  only:
    - merge_requests
    - schedules
  artifacts:
    when: always
    paths:
      - test-selenium.xml
    reports:
      junit: test-selenium.xml


test-library:
  stage: Tests
  before_script:
    - pip install pyenv
    - pip install pipenv
    - pipenv install
  script:
    - pipenv run pytest pages/main
  tags:
    - docker_shared
  only:
    - merge_requests
    - schedules
  artifacts:
    when: always
    paths:
      - test-selenium.xml
    reports:
      junit: test-selenium.xml

